### ISSUE TITLE
Able to log in with 2 clients to the same account.

### ISSUE THREAD

**Issue by Stand-up** [lare96/asteria-3.0#23]
Open 2 clients, put the same login details in both clients and as soon as server starts up hit login on both clients as fast as possible.

**Comment by lare96** [comment]
After 10 minutes of relentless clicking I finally managed to get it to work, with this issue I thought you meant being able to have the fully functional player on both windows. What happens instead is one of the windows goes to a black screen and times out after 5 seconds (which is expected). I wouldn't say it's an issue, but if you really want to "fix" this then add a check in the beginning of the create() method in the Player class that determines whether the player is already online (the check is already done on the networking thread, this issue is probably due to some sort of memory consistency error where threads have inconsistent views of data).
